# Generated by Django 3.1.3 on 2020-11-21 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20201010_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_kind1',
            field=models.CharField(choices=[('U', 'Undergraduate'), ('G', 'Graduated')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='post_kind2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
                'index_together': {('user', 'post')},
            },
        ),
    ]
